def raise_exception_msg():
    try :
        print(c)
    except NameError:
        print(NameError)